export const data = [
	{
		"checked": false,
		"id":"1",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"2",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"3",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"4",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"5",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"6",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"7",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"8",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"9",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"10",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"11",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"12",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"13",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"14",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"15",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"16",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"17",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"18",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"19",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},
]