export const data = [
	{
		"checked": false,
		"id":"1",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"1",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"1",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"1",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},{
		"checked": false,
		"id":"1",
		"placa": "ABC123",
		"marca": "Mazda",
		"modelo": "2",
		"kilometraje": "123.323",
		"transmision": "Automática",
		"tipo": "Automovil",
		"precio": 40000000,
	},
]